server:
  port: 8000

spring:
  application:
    name: apigateway-server
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            message: Global Filter Default Message Test
            pre: true
            post: true

      routes: # 개별 마이크로서비스 정보를 routes에 기입함
        - id: first-service
          uri: http://localhost:8001/
          predicates:
            - Path=/first-service/**
          filters:
#            - AddRequestHeader=fsreqhyml,fsreqhvyml
#            - AddResponseHeader=fsreshyml,fsreshvyml
            - CustomFilter
            - LogFilter

        - id: second-service
          uri: http://localhost:8002/
          predicates:
            - Path=/second-service/**
          filters:
            - CustomFilter2
